pipeline {
    agent {
        label "maven"
    }

    environment {
        ECR_REGISTRY = ""
        IMAGE_NAME = ""
        SONAR_URL = "https://sonarqube.gauravgirase.co.in"
    }

    stages {
        stage('Checkout'){
            steps {
                git branch: 'main', url: env.GIT_URL
            }
        }
        stage("Build"){
            steps {
                container("maven"){
                    sh 'mvn clean package -DskipTests'
                }
            }
        }
        stage("Test"){
            steps {
                container("maven"){
                    sh 'mvn test'
                }
            }
        }
        stage("SonarQube Analysis"){
            steps {
                withSonarQubeEnv('SonarQube'){
                    sh 'mvn sonar:sonar -Dsonar.projectKey=$JOB_NAME'
                }
            }
        }
        stage("Quality Gate"){
            steps {
                timeout(time: 5, unit: 'MINUTES'){
                    waitForQualityGate abortPipeline: true
                }
            }
        }
        stage("Build & Push Image"){
            steps {
                sh 'aws ecr get-login-password | docker login --username AWS --password-stdin $ECR_REGISTRY'
                sh 'docker build -t $ECR_REGISTRY/$IMAGE_NAME:$BUILD_NUMBER'
                sh 'docker push $ECR_REGISTRY/$IMAGE_NAME:$BUILD_NUMBER'
            }
        }
        stage("Update GitOps Repo"){
            steps {
                sh """
                git clone https://github.com/GauravGirase/gitops.git
                cd gitops && sed -i 's|image:.*|image:$ECR_REGISTRY/$IMAGE_NAME:$BUILD_NUMNER|' k8s/deployment.yaml
                git commit -am 'Update image to $BUILD_NUMBER' && git push
                """
            }
        }
    }
    post {
        always {
            junit 'target/surefire-reports/*.xml'
        }
        failure {
            echo "slack alert"
        }
        success {
            echo "slack notification"
        }
    }
}