apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore # defines where and how to access secrets
metadata:
  name: aws-secrets-manager
spec:
  provider:
    aws:
      service: SecretsManager
      region: ap-south-1
      auth:
        jwt: 
          serviceAccountRef:
            name: external-secrets
            namespace: external-secrets
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: jenkins-github-token
  namespace: jenkins
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-manager
    kind: ClusterSecretStore
  target:
    name: jenkins-github-token # the name of the Kubernetes secret that will be created
  data:
    - secretKey: token
      remoteRef:
        key: prod/jenkins/github-token # AWS Secrets Manager secret name/path
        property: token # the specific key inside that secret JSON.